In [1]:
# 下面的例子将展示Numpy的不同，假设一个Numpy数组包含100万个整数，还有一个
# 同样数据内容的python列表
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr *2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 22.5 ms, sys: 14.1 ms, total: 36.6 ms
Wall time: 40.8 ms
CPU times: user 768 ms, sys: 194 ms, total: 962 ms
Wall time: 968 ms


In [2]:
# 生成随机数
import numpy as np
data = np.random.randn(2,3)
data

array([[-0.71573026, -0.9699259 ,  0.45283487],
       [ 0.28190168,  0.69211139,  1.47397796]])

In [3]:
# 乘法
data * 10

array([[ -7.15730264,  -9.69925898,   4.52834869],
       [  2.81901684,   6.92111387,  14.73977964]])

In [4]:
data + data

array([[-1.43146053, -1.9398518 ,  0.90566974],
       [ 0.56380337,  1.38422277,  2.94795593]])

In [13]:
# 每一个数组都有一个shape属性，用来表征数组每一维度的数量，每一个数组都有一个dtype属性，用来描述数组的数据类型
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [15]:
# 用array函数生成数组，array函数接收任意的序列对象，生成一个新的包含传递数据的Numpy数组
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [16]:
# 嵌套序列，例如同等长度的列表，将会自动转换成多维数组
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# 我们可以通过ndim和shape属性来确认是不是二维数组
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int64')

In [21]:
# 除了np.array，还有很多其他函数可以创建新数组，给定长度及形状后，zeros可以一次性创造全0数组，ones，empty则可以创造一个没有初始化数值的
# 数组，想要创建高纬数组，则需要为shape传递一个元组
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [23]:
np.ones((2,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [24]:
np.empty((2,3))

array([[ 1.43146053,  1.9398518 ,  0.90566974],
       [ 0.56380337,  1.38422277,  2.94795593]])

In [28]:
np.empty((2,3,2))

array([[[  0.00000000e+000,   0.00000000e+000],
        [  2.96439388e-323,   0.00000000e+000],
        [  2.12199579e-314,   4.47032019e-038]],

       [[  5.45103013e-090,   8.60677331e-067],
        [  1.26138467e-076,   9.18032659e-072],
        [  3.99910963e+252,   8.34402697e-309]]])

In [29]:
# arange是python内置函数range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
# ndarray数据类型
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [32]:
arr2 = np.array([1,2,3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [33]:
# 你可以使用astype方法转换数组的数据类型
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [34]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [35]:
# 上面的例子，整数被转换成了浮点数，如果我把浮点数转换成整数，则小数点后的部分将被消除
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [38]:
arr_int = arr.astype(np.int32)
arr_int

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [39]:
arr_int.dtype

dtype('int32')

In [45]:
# 如果你有一个数组，里面的元素都是表达数字含义的字符串，也可以通过astype将字符串转换为数字
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [2]:
import numpy as np
int_array = np.arange(10)
calibers = np.array([.22, .380, .567], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [3]:
# 也可以使用类型代码来传入数据类型
empty_unit32 = np.empty(8, dtype='u4')
empty_unit32

array([         0, 3221225472,          0, 3221225472, 1622081538,
       1879050239, 1624315841,     133119], dtype=uint32)

In [5]:
# numpy数组算术，数组之所有重要是因为它允许你进行批量操作而无需任何for循环，numpy用户称这种特性为向量化。
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [6]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [7]:
arr + arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [8]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [9]:
arr * 0.5

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [10]:
# 同尺寸数组之间的比较，会产生一个布尔值数组
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [11]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

In [12]:
# 基础索引与切片
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

In [14]:
arr[5:8]

array([5, 6, 7])

In [16]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [17]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [18]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [19]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [20]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [22]:
arr2d[0][2]

3

In [31]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr3d[1][0]

array([7, 8, 9])

In [37]:
arr3d[1,1]

array([10, 11, 12])

In [38]:
# 数组的切片索引
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [39]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [40]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr2d[:2, :1]

array([[1],
       [4]])

In [43]:
arr2d[1, :2]

array([4, 5])

In [61]:
arr2d[:2, 2]

array([0, 0])

In [64]:
arr2d[:, :1]

array([[0],
       [0],
       [7]])

In [65]:
arr2d[:2, :1]

array([[0],
       [0]])

In [66]:
# 使用numpy.random中的randn函数来生成一些随机正太分布的数据
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])
data = np.random.randn(7, 4)
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'],
      dtype='<U4')

In [67]:
data

array([[ 1.87375805, -1.21766953,  0.49795342, -0.72098155],
       [ 0.82701193,  0.30830141, -1.08685803, -0.42354675],
       [-1.90400941, -1.0124874 ,  2.43194845, -1.1936125 ],
       [-0.79323733,  0.55133672,  1.0132063 , -0.01201107],
       [-0.29019487, -1.58366805, -1.48173481, -1.06377625],
       [-0.55065783, -0.80504392, -0.10009213,  0.63884651],
       [ 0.48816771, -0.1370207 ,  0.52401097,  0.00608488]])

In [68]:
# 假设每个每个人名都和data数组中的一行相对应，并且我们想要选中所有‘bob’对应的行，与数学操作类似，数组的比较操作（比如==）也是可以向
# 量化的。因此，比较names数组和字符串‘bob’会产生一个布尔数组：
names =='bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [69]:
data[names == 'bob']

array([[ 1.87375805, -1.21766953,  0.49795342, -0.72098155],
       [-0.79323733,  0.55133672,  1.0132063 , -0.01201107]])

In [70]:
data[names == 'bob', 2:]

array([[ 0.49795342, -0.72098155],
       [ 1.0132063 , -0.01201107]])

In [71]:
data[names == 'bob', 3]

array([-0.72098155, -0.01201107])

In [72]:
names != 'bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [73]:
data[~(names == 'bob')]

array([[ 0.82701193,  0.30830141, -1.08685803, -0.42354675],
       [-1.90400941, -1.0124874 ,  2.43194845, -1.1936125 ],
       [-0.29019487, -1.58366805, -1.48173481, -1.06377625],
       [-0.55065783, -0.80504392, -0.10009213,  0.63884651],
       [ 0.48816771, -0.1370207 ,  0.52401097,  0.00608488]])

In [74]:
cond = names == 'bob'
data[~cond]

array([[ 0.82701193,  0.30830141, -1.08685803, -0.42354675],
       [-1.90400941, -1.0124874 ,  2.43194845, -1.1936125 ],
       [-0.29019487, -1.58366805, -1.48173481, -1.06377625],
       [-0.55065783, -0.80504392, -0.10009213,  0.63884651],
       [ 0.48816771, -0.1370207 ,  0.52401097,  0.00608488]])

In [75]:
# 当要选择三个名字中的两个时，可以对多个布尔值条件进行联合，需要使用数学操作符如：&(and) 和 (or)
mask = (names == 'bob') | (names == 'will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [76]:
data[mask]

array([[ 1.87375805, -1.21766953,  0.49795342, -0.72098155],
       [-1.90400941, -1.0124874 ,  2.43194845, -1.1936125 ],
       [-0.79323733,  0.55133672,  1.0132063 , -0.01201107],
       [-0.29019487, -1.58366805, -1.48173481, -1.06377625]])

In [77]:
data[data < 0] = 0
data

array([[ 1.87375805,  0.        ,  0.49795342,  0.        ],
       [ 0.82701193,  0.30830141,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.43194845,  0.        ],
       [ 0.        ,  0.55133672,  1.0132063 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.63884651],
       [ 0.48816771,  0.        ,  0.52401097,  0.00608488]])

In [78]:
data[names != 'joe'] = 7
data

array([[  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [  8.27011929e-01,   3.08301405e-01,   0.00000000e+00,
          0.00000000e+00],
       [  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          6.38846512e-01],
       [  4.88167709e-01,   0.00000000e+00,   5.24010971e-01,
          6.08487906e-03]])

In [79]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [80]:
# 为了选出一个符合特定顺序的子集，你可以简单的通过传递一个包含指明所需顺序的列表或数组来完成
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [81]:
# 如果使用负的索引，将从尾部进行选择
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [82]:
# 传递多个索引数组时情况有些许不同，这样会根据每个索引元素对应选出一个一维数组
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [84]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [90]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [91]:
# 转置是一种特殊的数据重组形式，可以返回底层数据的视图而不需要复制任何内容，数组拥有transpose方法，也有特殊的T属性
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [92]:
# 当进行矩阵计算时，你可能会经常进行一些特定操作，比如：当计算矩阵内积会使用np.dot：
arr = np.random.randn(6, 3)
arr

array([[ 0.12576141,  0.52510511, -2.21597379],
       [ 1.03689219, -0.33174877,  1.10543214],
       [-0.32510187, -0.21148948,  1.46438603],
       [ 1.22907602, -0.40503518, -0.95580632],
       [-2.05091041, -1.43150816, -1.22714024],
       [-1.09443947, -1.5302594 ,  0.62144407]])

In [93]:
np.dot(arr.T, arr)

array([[  8.11131168,   3.90365812,   1.05331847],
       [  3.90365812,   4.98548336,  -0.64722134],
       [  1.05331847,  -0.64722134,  11.08257814]])